#!/bin/bash

# Recursively find and replace in files
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Terra/Iq/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/TERRA/IQ/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/terra-money/web4/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/terra/iq/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Luna/Biq/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/luna/biq/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/LUNA/BIQ/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/USD/BUSD/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/usd/BUSD/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Usd/Busd/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/KRW/BKRW/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/krw/bkrw/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Krw/Bkrw/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/SDR/BSDR/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Sdr/Bsdr/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/sdr/bsdr/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/CNY/BCNY/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Cny/Bcny/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/cny/bcny/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/JPY/BJPY/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Jpy/Bjpy/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/jpy/bjpy/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/EUR/BEUR/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/eur/beur/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Eur/Beur/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/GBP/BGBP/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/gbp/bgbp/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Gbp/Bgbp/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/MNT/BMNT/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/mnt/bmnt/g'
find . -type f -name "*.go" -print0 | xargs -0 sed -i '' -e 's/Mnt/Bmnt/g'
